name: test

on: [pull_request]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - name: Install Node.js
        env:
          NODE_VERSION: 14.17.0
        run: export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use && nvm install
      - name: Install dependencies
        run: npm install
      - name: Lint source code with ESLint
        run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    container:
      image: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Cache node.js modules
        uses: actions/cache@v2
        env:
          cache-name: npm-${{ hashFiles('package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-key: |
            ${{ env.cache-name }}
      - name: Install dependencies
        run: npm install
      - name: Lint source code with Prettier
        run: npm run check:format

  build:
    name: Prettier
    runs-on: ubuntu-latest
    container:
      image: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Storing artifacts
        uses: actions/upload-artifacts@v2
        with:
          name: build
          path: build/*
      - name: Cache node.js modules
        uses: actions/cache@v2
        env:
          cache-name: npm-${{ hashFiles('package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-key: |
            ${{ env.cache-name }}
      - name: Install dependencies
        run: npm install
      - name: Lint source code with Prettier
        run: npm run build
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifacts@v2
        with:
          name: build
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      - name: Copy files
        run: |
          rsync -a --progress --human-readable --delete \
          --exclude-from '.gitignore' \
          --exclude .gitignore \
          --exclude .git \
          . deploy@77.73.70.75:~/realworld/
          ssh deploy@77.73.70.75 "pushd ~/realworld && npm install && pm2 restart realworld && popd"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
